
version: 2
jobs:
  build:
    working_directory: ~/code
    parallelism: 4
    docker:
      - image: circleci/android:api-26
    environment: &proxy_env
      _JAVA_OPTIONS: -Xmx3g -Xms3g
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=1
    steps:
      - checkout
      - restore_cache:
          keys:
            - ndk_r16b-dependencies
      - run:
          name: Update ndk_r16b
          no_output_timeout: 30m 
          command: |
            if [ ! -d /home/circleci/android-ndk-r16b/ ]; then
              sudo apt-get update
              sudo apt-get install -y zip unzip libncurses5
              wget https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip
              unzip android-ndk-r16b-linux-x86_64.zip -d /home/circleci
            fi
      - save_cache:
          paths:
            - /home/circleci/android-ndk-r16b/
          key: ndk_r16b-dependencies
      - run:
          name: Update sdk licenses
          command: |
            yes | sdkmanager --licenses || true
            yes | sdkmanager --update  || true
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Build 
          command: ./gradlew clean assembleDebug
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
